language: node_js

node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"

services:
  - docker
  - postgresql

before_script:
  - psql -c 'create database puresql_test;' -U postgres

# after_script:
#  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
